### ISSUE TITLE
Failure to launch on OSX

### ISSUE THREAD

**Issue by lily-mara** [huynhquancam/worque#6]
After a fresh install on OSX, I get the following output on running `worque todo`

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1545:in `path': no implicit conversion of nil into String (TypeError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1545:in `block in fu_list'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1545:in `map'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1545:in `fu_list'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:199:in `mkdir_p'
        from /Library/Ruby/Gems/2.0.0/gems/worque-0.1.4/lib/worque/utils/command.rb:9:in `mkdir'
        from /Library/Ruby/Gems/2.0.0/gems/worque-0.1.4/lib/worque/command/todo.rb:13:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/worque-0.1.4/lib/worque/command/todo.rb:23:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/worque-0.1.4/lib/worque/cli.rb:18:in `todo'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/worque-0.1.4/bin/worque:6:in `<top (required)>'
        from /usr/bin/worque:23:in `load'
        from /usr/bin/worque:23:in `<main>'

```

This is using ruby 2.0.0p481 and gem 2.0.14, OSX 10.10.5

**Comment by qcam** [comment]
@natemara did you have `WORQUE_PATH` env var set?

But seems like we need better error message.

**Comment by lily-mara** [comment]
That did it... I need to do a better job reading instructions.
